package com.easypump.infrastructure;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * All System environment variables must be kept here for auditing purpose
 */
@AllArgsConstructor
@Getter
public enum EnvironmentVariable {
    EASY_PUMP_JWT_SECRET_KEY("EASY_PUMP_JWT_SECRET_KEY"),
    JWT_EXPIRATION_TIME_MINUTES("JWT_EXPIRATION_TIME_MINUTES"),
    EASY_PUMP_SERVER_PORT("EASY_PUMP_SERVER_PORT"),
    EASY_PUMP_DB_HOST("EASY_PUMP_DB_HOST"),
    EASY_PUMP_DB_PORT("EASY_PUMP_DB_PORT"),
    EASY_PUMP_DB_USERNAME("EASY_PUMP_DB_USERNAME"),
    EASY_PUMP_DB_PASSWORD("EASY_PUMP_DB_PASSWORD"),
    EASY_PUMP_DB_NAME("EASY_PUMP_DB_NAME"),
    AWS_EASY_PUMP_SECRET_KEY("AWS_EASY_PUMP_SECRET_KEY"),
    AWS_EASY_PUMP_ACCESS_KEY("AWS_EASY_PUMP_ACCESS_KEY"),
    AWS_EASY_PUMP_REGION("AWS_EASY_PUMP_REGION"),
    ENVIRONMENT("ENVIRONMENT"),
    AWS_ENABLED("AWS_ENABLED"),
    AWS_TEST_S3_BUCKET("AWS_TEST_S3_BUCKET"),
    AWS_DEVELOPMENT_S3_BUCKET("AWS_DEVELOPMENT_S3_BUCKET"),
    AWS_PRODUCTION_S3_BUCKET("AWS_PRODUCTION_S3_BUCKET");
    private final String value;
}
