package com.easypump.model.role;

public enum PermissionEnum {
    SUPER_PERMISSION,
    AUTHENTICATED,

    READ_USER_ACCOUNTS,
    UPDATE_USER_ACCOUNTS,
    APPROVE_USER_ACCOUNTS,
    ACTIVATE_USER_ACCOUNTS,
    CLOSED_USER_ACCOUNTS,

    READ_APPLICATION_USERS,
    CREATE_APPLICATION_USERS,
    UPDATE_APPLICATION_USERS,
    CLOSE_APPLICATION_USERS,

    READ_USER_PERMISSION,
    READ_USER_ROLES,
    CREATE_USER_ROLES,
    UPDATE_USER_ROLES,
    DELETE_USER_ROLES,

    READ_BRANCHES,
    CREATE_BRANCHES,
    UPDATE_BRANCHES,
    CLOSE_BRANCHES,

    READ_COMPANIES,
    CREATE_COMPANIES,
    UPDATE_COMPANIES,
    CLOSE_COMPANIES,

    READ_RECIPIENTS,
    CREATE_RECIPIENTS,
    UPDATE_RECIPIENTS,
    CLOSE_RECIPIENTS,

    READ_WALLETS,
    CREATE_WALLETS,
    UPDATE_WALLETS,
    ACTIVATE_WALLETS,
    DEACTIVATE_WALLETS,
    TOP_UP_WALLETS,
    APPLY_WALLET_CHARGES,

    READ_WALLET_CHARGES,
    CREATE_WALLET_CHARGES,
    UPDATE_WALLET_CHARGES,
    ACTIVATE_WALLET_CHARGES,
    DEACTIVATE_WALLET_CHARGES


}
